# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='data de nascimento')),
                ('age', models.IntegerField(editable=False, verbose_name='idade')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone secundário')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='rua')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='estado')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='profissão')),
                ('insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='convênio')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='número do convênio')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('EVALUATION', 'Em Avaliação'), ('DISCHARGED', 'Alta')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('general_notes', models.TextField(blank=True, null=True, verbose_name='observações gerais')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='queixa principal')),
                ('current_illness', models.TextField(blank=True, null=True, verbose_name='história da doença atual')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='histórico médico')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='medicamentos em uso')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='alergias')),
                ('lifestyle', models.TextField(blank=True, null=True, verbose_name='estilo de vida')),
                ('physical_assessment', models.TextField(blank=True, null=True, verbose_name='avaliação física')),
                ('last_visit_date', models.DateTimeField(blank=True, null=True, verbose_name='data da última visita')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
