# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL, verbose_name='fisioterapeuta responsável'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic', verbose_name='clínica'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'status'], name='patients_pa_clinic__d8d066_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['cpf'], name='patients_pa_cpf_e307a5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['assigned_therapist'], name='patients_pa_assigne_0fdd70_idx'),
        ),
    ]
