# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('type', models.CharField(choices=[('INITIAL_EVALUATION', 'Avaliação Inicial'), ('REASSESSMENT', 'Reavaliação'), ('TREATMENT_SESSION', 'Sessão de Tratamento'), ('DISCHARGE', 'Alta'), ('RETURN', 'Retorno')], max_length=30, verbose_name='tipo')),
                ('subjective', models.TextField(blank=True, null=True, verbose_name='subjetivo')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='objetivo')),
                ('assessment', models.TextField(blank=True, null=True, verbose_name='avaliação')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='plano')),
                ('exercises', models.TextField(blank=True, null=True, verbose_name='exercícios prescritos')),
                ('next_visit', models.DateTimeField(blank=True, null=True, verbose_name='próxima visita')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('can_edit', models.BooleanField(default=True, verbose_name='pode editar')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['-date'],
            },
        ),
    ]
