# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['clinic', 'patient'], name='consultatio_clinic__9d5310_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date'], name='consultatio_date_0bc67a_idx'),
        ),
    ]
