# Generated by Django 5.0.1 on 2025-11-05 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'clínica',
                'verbose_name_plural': 'clínicas',
                'ordering': ['name'],
            },
        ),
    ]
