# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file_name', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('file_url', models.URLField(max_length=500, verbose_name='URL do arquivo')),
                ('file_size', models.IntegerField(verbose_name='tamanho do arquivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='tipo MIME')),
                ('category', models.CharField(choices=[('EXAME_IMAGEM', 'Exame de Imagem'), ('EXAME_LABORATORIAL', 'Exame Laboratorial'), ('RECEITA', 'Receita Médica'), ('ATESTADO', 'Atestado'), ('CONSENTIMENTO', 'Termo de Consentimento'), ('ANAMNESE', 'Anamnese'), ('RELATORIO_EVOLUCAO', 'Relatório de Evolução'), ('OUTROS', 'Outros')], max_length=30, verbose_name='categoria')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
