# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['clinic', 'patient'], name='documents_d_clinic__f2704b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_2c6923_idx'),
        ),
    ]
