# Generated by Django 5.0.1 on 2025-11-05 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='senha')),
                ('name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('crm', models.CharField(blank=True, help_text='Registro no conselho profissional', max_length=20, null=True, verbose_name='CRM/CREFITO')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('PHYSIOTHERAPIST', 'Fisioterapeuta'), ('RECEPTIONIST', 'Recepcionista')], default='PHYSIOTHERAPIST', max_length=20, verbose_name='função')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superusuário')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='último login')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clinics.clinic', verbose_name='clínica')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['clinic', 'role'], name='users_user_clinic__15ca76_idx'), models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx')],
            },
        ),
    ]
